# GitLab CI/CD Pipeline for Spring Boot Backend and Vue Frontend

stages:
  - build
  - test
  - package
  - deploy

variables:
  MAVEN_OPTS: '-Dmaven.repo.local=.m2/repository'
  MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end --show-version'
  NODE_VERSION: '22'
  PNPM_VERSION: '10.8.0'

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/
    - frontend/.pnpm-store/

build-backend:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - backend/target/classes/
    expire_in: 1 hour
  only:
    - merge_requests
    - main
    - develop

test-backend:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - backend/target/surefire-reports/TEST-*.xml
    paths:
      - backend/target/surefire-reports/
  only:
    - merge_requests
    - main
    - develop

package-backend:
  stage: package
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - cd backend
    - mvn $MAVEN_CLI_OPTS package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 week
  only:
    - main
    - develop

build-frontend:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm install -g pnpm@${PNPM_VERSION}
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 hour
  only:
    - merge_requests
    - main
    - develop

lint-frontend:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm install -g pnpm@${PNPM_VERSION}
    - pnpm install --frozen-lockfile
    - pnpm run lint
  only:
    - merge_requests
    - main
    - develop

test-frontend:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - cd frontend
    - npm install -g pnpm@${PNPM_VERSION}
    - pnpm install --frozen-lockfile
    - pnpm vitest run
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    when: always
    reports:
      junit:
        - frontend/test-results.xml
      coverage_report:
        coverage_format: cobertura
        path: frontend/coverage/cobertura-coverage.xml
  only:
    - merge_requests
    - main
    - develop
